# Generated by Django 4.0.6 on 2022-08-09 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0002_game_name_game_score_userprofileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('age', models.IntegerField(null=True)),
                ('best_score', models.IntegerField()),
                ('base_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UpcommingMatchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_name', models.CharField(max_length=120)),
                ('sports_title', models.CharField(max_length=120)),
                ('start_time', models.DateTimeField()),
                ('home_team', models.CharField(max_length=120)),
                ('away_team', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='best_player',
            field=models.CharField(default=2, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phone_no',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='BetBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upcomming_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betapp.upcommingmatchs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betapp.userprofileinfo')),
            ],
        ),
    ]
