# Generated by Django 4.0.6 on 2022-08-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0003_players_upcommingmatchs_game_best_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='betbooking',
            name='price',
            field=models.CharField(default=3, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='betbooking',
            name='upcomming_match',
            field=models.CharField(max_length=120),
        ),
    ]
